### ISSUE TITLE
Late game resources balance

### ISSUE THREAD

**Issue by AliusDieMorietur** [FAForever/UnitDB#10]
Add please for seraphim`s 'Support Armored Command Unit' Enhancement:  [RCH] Resource Allocation System. There is no reason for them to don`t have it. Everyone tired from asking for other nation`s engineer to build ACU with RCH.

**Comment by shalkya** [comment]
this is not the good repository for this kind of issues. 
this PR aim to close the gap between the ras scu and sera scus : https://github.com/FAForever/fa/pull/2866
