### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/UnitDB#13]
This repository is currently unmaintained. If you are interested in becoming maintainer of this repository, please post here.

**Comment by PViddy72** [comment]
I'm willing to do the maintenance to get the Rackover/official UnitDB updated and working.  
Actually, I've already downloaded the code from the Github and created a working & updated version of the site on my local computer.

**Comment by Brutus5000** [comment]
@PViddy72  I'm awaiting your first PRs then :)

**Comment by PViddy72** [comment]
This is being deployed to a Windows system, correct? The original files had Unix line endings.  Should I convert everything to Windows line endings in my branch?

**Comment by Brutus5000** [comment]
No, this is deployed to Linux machines via docker container.

**Comment by PViddy72** [comment]
Do I need some permissions to create a branch?  GitHub is saying it will create a 'fork' instead.

**Comment by Brutus5000** [comment]
@PViddy72 you should have received an invite now.

**Comment by PViddy72** [comment]
I received an invite.  I don't think it changed my access permissions in any way.
I'm a GitHub newbie, so I'm still struggling to understand how all this works.

I was able to commit my changes to my forked version and generated a Pull Request back to the FAF master.  Hopefully, that will be sufficient.

**Comment by PViddy72** [comment]
I made the suggested changes in the latest commit to the fork.

**Comment by Crotalus** [comment]
Nice, the UnitDB needs "some" love 😄 

If you have the changes in your own repo/branch you can create a pull request in this repo and that way get the code merged

**Comment by PViddy72** [comment]
Code is merged. When does this get deployed?  Does it go to a test server first?
Someone will have to run the update.php via a browser.
You would add "/update.php?debug=1" to the web address.

**Comment by Brutus5000** [comment]
- An admin of the repo builds a release ([link](https://github.com/FAForever/UnitDB/releases/tag/v1.4.1)).
- This triggers the CI to build a fresh Docker container ([link](https://github.com/FAForever/UnitDB/actions/runs/8607045420)).
- The new docker container is detected by a bot in our infrastructure repo ([link](https://github.com/FAForever/gitops-stack/pull/37)).
- After the PR is merged it is auto-deployed to the test environment [unitdb.faforever.xyz](https://unitdb.faforever.xyz) with a delay of a few minutes.
- The Kubernetes pod has a config that is runs the update command after start ([link](https://github.com/FAForever/gitops-stack/blob/3048c7fe8a671b085a44c3851a22b946f1549a71/apps/faf-unitdb/templates/deployment.yaml#L30)).

Deployment to prod is different and out of the scope here.

**Comment by PViddy72** [comment]
I checked out the test environment.  Has the update already run?  If so, something went wrong.

**Comment by Brutus5000** [comment]
Please PM me your email in Discord or FAF forum. This is not the right place for discussions.
Also: yes 1.4.1 (the latest version) is deployed on test.
