### ISSUE TITLE
Automated deployment to update viewer when a release on `faforever/fa` happens

### ISSUE THREAD

**Issue by Garanas** [FAForever/UnitDB#21]
I've been working on various Github actions to update, build and deploy the relative old [spooky unit database](https://github.com/FAForever/spooky-db). See also the [actions](https://github.com/FAForever/spooky-db/actions) page. We can now click on a button to update it. Soon [it will be fully automatic whenever we do a release](https://github.com/FAForever/spooky-db/issues/127).

I'm hoping to achieve the same with this repository. That way when we release a new game version all the (current) unit viewers remain in sync automatically, forever! However, I'm not exactly familiar with the setup of this repository and specifically with the use of docker.

**Comment by Garanas** [comment]
I noticed https://github.com/FAForever/UnitDB/issues/13 where @Brutus5000 and @PViddy72 discuss about being a maintainer. The discussion was relatively recent, here's me hoping that Pviddy72 is around and interested to help set this up 😃

**Comment by Brutus5000** [comment]
There is already a feature for that. It was supposed to be called in the api. But it doesn't work due to a concurrency bug.

The github action of the fa rep just needs to trigger the update.php with the right version and a secret.

**Comment by Garanas** [comment]
That is good then 👍 , can I or perhaps Pviddy72 help with debugging the concurrency bug somehow? And what end point (where `update.php` is) do we need to trigger exactly?

**Comment by Brutus5000** [comment]
https://unitdb.faforever.com/update.php?version=${BRANCH}&token=${UNITDB_UPGRADE_SECRET}
The concurrency issue was in the API. If you trigger it via github action, we don't need to go through the API anymore.
