### ISSUE TITLE
unitdatabase not up to date

### ISSUE THREAD

**Issue by shalkya** [FAForever/UnitDB#5]
comparison with spooky unitdatabase
![image](https://user-images.githubusercontent.com/11618427/58352458-d9ab6680-7e6b-11e9-95da-5f9d26e9d9c6.png)
look at BT and price of ML. Those were changed last balance patch several months ago.

**Comment by shalkya** [comment]
was updated manually by brutus

**Comment by louvenarde** [comment]
Has something to do with the auto-update trigger failing on prod, nothing to do with the actual database
