### ISSUE TITLE
Correcting the values and use of values

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/UnitDB#6]
Key:
Muzzle Salvo Size (MSS)
Fire cycle (Number of projectiles / shot )

The changes :

The use of Projectiles Per Fire should be -> Muzzle Salvo Size use this for number of shots

IF MSS = 1, count all muzzlebones and use the total number of muzzlebones in this weapon as the Fire cycle
IF MSS ≠ 1, count all rackbones and multiply by MSS for Fire cycle

We can put that into the DB to correct the numbers.

**Comment by louvenarde** [comment]
Hopefully fixed in https://github.com/FAForever/UnitDB/commit/fe6f6f14797c114abce4b2accc2ea4dcb88cf9c2
